Repository jenkins-x/environment-tekton-weasel-staging, pull requests merged in 2019-10, with the labels that each got.

#23 fix: add a staging secret
  env/values.yaml
Labels: approved, lgtm, size/XS

#28 chore: removed status-badge app from staging
  env/requirements.yaml
Labels: approved, size/XS

#33 fix: point ingress at the correct service name
  env/templates/tenant-service-ingress.yaml
Labels: approved, lgtm, size/XS

#36 chore: add TLS enabled ingress for arcalos ui
  env/templates/arcalosui-ingress.yaml
Labels: approved, lgtm, size/S

#51 chore: increase tenant service and ui replicas
  env/values.yaml
Labels: approved, lgtm, size/XS

#55 chore: add staging vault uri for new github app
  env/values.yaml
Labels: approved, lgtm, size/XS

#58 chore: add github app ingress and try to disable exposecontroller job
  env/requirements.yaml
  env/templates/gh-app-ingress.yaml
Labels: approved, size/M

#60 chore: remove basic auth for github app as not needed yet
  env/templates/gh-app-ingress.yaml
Labels: approved, lgtm, size/XS

#62 fix: release - seems the jobs are still needed
  env/requirements.yaml
Labels: approved, lgtm, size/XS
